---
name: Build Windows (.NET Framework)

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:

  build:

    runs-on: windows-latest

    env:
      SOLUTION_PATH: ProgramaOTLauncher.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Add MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    # Install .NET SDK only for restore (PackageReference)
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore NuGet packages
      run: dotnet restore $env:SOLUTION_PATH

    - name: Build solution (Release)
      run: msbuild $env:SOLUTION_PATH /t:Build /p:Configuration=Release

    - name: Upload Launcher artifact (Release bin)
      uses: actions/upload-artifact@v4
      with:
        name: ProgramaOT-Launcher-bin-Release
        path: |
          ProgramaOTLauncher/bin/Release/

    - name: Upload Updater artifact (Release bin)
      uses: actions/upload-artifact@v4
      with:
        name: Updater-bin-Release
        path: |
          Updater/bin/Release/
